name: Workflow Run

on:
    workflow_run:
        workflows: [Workflow 1]
        types:
          - completed

jobs:
    job:
        runs-on: ubuntu-latest
        steps:
          - run: echo "The secret is ${{ secrets.SECRET }}"
          - name: Checkout Repository
            uses: actions/checkout@v4
            with:
                fetch-depth: 0
          - run: cat file.txt
          - run: echo ${{ github.event.pull_request.head.ref }}